# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f3fdccd51dd39f1f840c2c5d99548b7b8ba6f7803a83533420f8062cc013ddd464b60804caecb6dfdedf13749e3137fc084804d12ca5aacd335e9cefbc5c1e

test:
  secret_key_base: a2993258fcef5d2d685fe51919f64a02d1522d1a8727339af4d894e27944b4068cd118d8d081aa28ad43bff7467037e7b9a214da13f96d858b582e98ecebe430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
