# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95a69aa765e9464a1c2123dde28edab3456c9539c97dd1f4506cd88c2f6dabb9fc860af67ce52fe11c110f69ac2ef62ff2b193899cf72189f40adc9225fb44e

test:
  secret_key_base: 49903c2ed90790494c42333cc170a48de2e025d290b8a8843f42f3003f3cd5c1f4254bdf7fed8125d7dc7c17f5973e2ab0581512536f9e114c3104a8be003a6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
